[supabase]
url = 'https://mkcnfwydvimltrzyptjo.supabase.co'
key = 'eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1rY25md3lkdmltbHRyenlwdGpvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MDg1NTI5OTksImV4cCI6MjAyNDEyODk5OX0.aWDMRS90k_7DmdyFTLKl2gdPLbIO7M94kvs2lDxgGvY'